# Generated by Django 5.1.3 on 2024-12-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_adminreg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_adminreg',
        ),
    ]
