# Generated by Django 5.1.3 on 2025-01-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_subcategory',
            name='subcategory_name',
            field=models.CharField(max_length=50),
        ),
    ]
