# Generated by Django 5.1.3 on 2025-01-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_batch',
            name='batch_name',
            field=models.CharField(default='Unnamed Batch', max_length=100),
        ),
    ]
