# Generated by Django 5.1.3 on 2025-01-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_alter_tbl_batch_batch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_batch',
            name='batch_name',
            field=models.CharField(max_length=100),
        ),
    ]
