# Generated by Django 5.1.3 on 2025-04-07 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_email', models.CharField(max_length=50)),
                ('student_contact', models.CharField(max_length=50)),
                ('student_address', models.CharField(max_length=50)),
                ('student_password', models.CharField(max_length=50)),
                ('student_photo', models.FileField(upload_to='assets/admin/photo')),
                ('student_status', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_batch')),
            ],
        ),
    ]
