# Generated by Django 5.1.3 on 2025-02-27 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0006_tbl_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=50)),
                ('complaint_content', models.CharField(max_length=50)),
                ('complaint_replay', models.CharField(max_length=50)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_alumni')),
            ],
        ),
    ]
