# Generated by Django 5.1.3 on 2025-03-18 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0003_tbl_rating'),
        ('Guest', '0006_tbl_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('alumin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_alumni')),
            ],
        ),
    ]
