# Generated by Django 5.2 on 2025-04-13 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0004_tbl_payment'),
        ('Company', '0005_tbl_internship_tbl_jobpost'),
        ('Guest', '0006_tbl_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='internship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.tbl_internship'),
        ),
        migrations.AddField(
            model_name='tbl_request',
            name='jobpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.tbl_jobpost'),
        ),
        migrations.AddField(
            model_name='tbl_request',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='alumni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_alumni'),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.tbl_workshop'),
        ),
    ]
