# Generated by Django 5.2 on 2025-04-13 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0005_tbl_request_internship_tbl_request_jobpost_and_more'),
        ('Guest', '0006_tbl_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_achivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achivement_title', models.CharField(max_length=50)),
                ('achivement_description', models.CharField(max_length=50)),
                ('achivement_photo', models.FileField(upload_to='Assets/achivements/photo')),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_alumni')),
            ],
        ),
    ]
