# Generated by Django 5.2 on 2025-04-15 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_student'),
        ('Alumni', '0006_tbl_achivements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_request',
            name='user',
        ),
        migrations.AddField(
            model_name='tbl_request',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_student'),
        ),
    ]
