# Generated by Django 5.1.3 on 2025-04-19 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0007_remove_tbl_request_user_tbl_request_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='complaint_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
