# Generated by Django 5.1.3 on 2025-04-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0008_tbl_complaint_complaint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
