# Generated by Django 5.2 on 2025-04-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0009_alter_tbl_complaint_complaint_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='complaint_status',
            field=models.IntegerField(default=0),
        ),
    ]
