# Generated by Django 5.1.3 on 2025-02-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(max_length=50)),
                ('workshop_description', models.CharField(max_length=50)),
                ('workshop_photo', models.FileField(upload_to='assets/workshop/photo')),
            ],
        ),
    ]
