# Generated by Django 5.1.3 on 2025-02-20 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0002_delete_tbl_workshop'),
        ('Guest', '0006_tbl_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(max_length=50)),
                ('workshop_description', models.CharField(max_length=50)),
                ('workshop_photo', models.FileField(upload_to='assets/workshop/photo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.CharField(max_length=50)),
                ('request_status', models.IntegerField(default=0)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_alumni')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.tbl_workshop')),
            ],
        ),
    ]
