# Generated by Django 5.1.3 on 2025-03-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
