# Generated by Django 5.2 on 2025-04-13 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_delete_tbl_request'),
        ('Guest', '0006_tbl_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_title', models.CharField(max_length=50)),
                ('internship_description', models.CharField(max_length=50)),
                ('internship_date', models.DateField(auto_now_add=True)),
                ('internship_photo', models.FileField(upload_to='Assets/internship/photo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_jobpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('job_description', models.CharField(max_length=50)),
                ('job_date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
            ],
        ),
    ]
