# Generated by Django 5.2 on 2025-04-15 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0013_tbl_student'),
        ('Guest', '0006_tbl_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('alumni_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumni_from', to='Guest.tbl_alumni')),
                ('alumni_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumni_to', to='Guest.tbl_alumni')),
                ('student_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_from', to='Admin.tbl_student')),
                ('student_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_to', to='Admin.tbl_student')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_friend_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.IntegerField(default=0)),
                ('alumini', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_alumni')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_student')),
            ],
        ),
    ]
