# Generated by Django 5.1.3 on 2025-01-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_alter_tbl_subcategory_subcategory_name'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_reg',
            new_name='tbl_user',
        ),
    ]
