# Generated by Django 5.1.3 on 2025-01-23 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_alter_tbl_batch_batch_name'),
        ('Guest', '0002_rename_tbl_reg_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni_name', models.CharField(max_length=50)),
                ('alumni_email', models.CharField(max_length=50)),
                ('alumni_contact', models.CharField(max_length=50)),
                ('alumni_address', models.CharField(max_length=50)),
                ('alumni_photo', models.FileField(upload_to='Assets/alumni/photo/')),
                ('alumni_password', models.CharField(max_length=50)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_batch')),
            ],
        ),
    ]
