# Generated by Django 5.1.3 on 2025-01-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_alumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_alumni',
            name='alumni_photo',
            field=models.FileField(upload_to='assets/alumni/photo'),
        ),
    ]
