# Generated by Django 5.1.3 on 2025-01-30 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_alter_tbl_batch_batch_name'),
        ('Guest', '0005_tbl_alumni_alumni_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_email', models.CharField(max_length=50)),
                ('company_contact', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=50)),
                ('company_password', models.CharField(max_length=50)),
                ('company_photo', models.FileField(upload_to='assets/company/photo')),
                ('company_logo', models.FileField(upload_to='assets/company/logo')),
                ('company_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
