# Generated by Django 5.2 on 2025-04-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_friend_request',
            name='alumini',
        ),
        migrations.RemoveField(
            model_name='tbl_friend_request',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_chat',
        ),
        migrations.DeleteModel(
            name='tbl_friend_request',
        ),
    ]
